package console

func (s *Server) routes() {
	s.router.Get("/api/status", s.handleStatus)
	s.router.Get("/api/audit", s.handleAudit)
	s.router.Get("/api/audit/summary", s.handleAuditSummary)
	s.router.Get("/api/store", s.handleStore)
	s.router.Get("/api/power/curve", s.handlePowerCurve)
	s.router.Get("/api/wind/trend", s.handleWindTrend)
	s.router.Get("/api/pitch/status", s.handlePitchStatus)
	s.router.Get("/api/brake/status", s.handleBrakeStatus)
	s.router.Get("/api/cable/status", s.handleCableStatus)
	s.router.Get("/api/tower/status", s.handleTowerStatus)
	s.router.Post("/api/pitch/move", s.handlePitchMove)
	s.router.Post("/api/pitch/ramp", s.handlePitchRamp)
	s.router.Post("/api/pitch/demand", s.handlePitchDemand)
	s.router.Post("/api/pitch/feather", s.handlePitchFeather)
	s.router.Post("/api/pitch/reset", s.handlePitchReset)
	s.router.Post("/api/yaw/turn", s.handleYawTurn)
	s.router.Post("/api/yaw/apply", s.handleYawApply)
	s.router.Post("/api/yaw/untwist", s.handleYawUntwist)
	s.router.Post("/api/brake/pressure", s.handleBrakePressure)
	s.router.Post("/api/brake/charge", s.handleBrakeCharge)
	s.router.Post("/api/brake/latch", s.handleBrakeLatch)
	s.router.Post("/api/wind/sample", s.handleWindSample)
	s.router.Post("/api/power/target", s.handleLoadSetpoint)
	s.router.Post("/api/cutin", s.handleCutIn)
	s.router.Post("/api/breaker/open", s.handleBreakerOpen)
	s.router.Post("/api/limit", s.handleLimit)
	s.router.Post("/api/trip", s.handleTrip)
	s.router.Post("/api/grid/voltage", s.handleGridVoltage)
	s.router.Post("/api/recalibrate", s.handleRecalibrate)
	s.router.Post("/api/tower/vibration", s.handleVibration)
}
